### ISSUE TITLE
Metadata Issue in automatic traslation

### ISSUE THREAD

**Issue by Noradrex** [MicrosoftDocs/OfficeDocs-SharePoint#623]
There is a problem in the page _"sharepoint/branding-sharepoint-online-sites-modern-experience"_ when accesed from a localized URL like _ES-ES_.
In that case, the content is automatically translated showing the "hidden" metadata. For example:
https://docs.microsoft.com/es-es/sharepoint/branding-sharepoint-online-sites-modern-experience

This wrong behaviour is not observed in the EN-US version, neither can be fixed deactivating the auto-translate, like in the image attached.

![captura](https://user-images.githubusercontent.com/2478701/52124388-54d0de80-2629-11e9-9930-9510a33072de.PNG)

**Comment by dariomws306** [comment]
Hi @Noradrex , thank you for your feedback!

@OfficeGlobal, could you check this please? Thank you!

**Comment by OfficeGlobal** [comment]
Hello @dariomws306,

 we've checked the file, problem is in the source article. Metadata section is not correctly ended.
It contains "..." instead of "---"

Once fixed in the source, all INTL pages will be properly updated / displayed

Thank you

**Comment by OfficeGlobal** [comment]
Note: we have found badly formatted metadata in few more articles
 - SharePoint\SharePointOnline\get-started-with-modern-search-experience.md
 - SharePoint\SharePointOnline\guide-to-sharepoint-modern-experience.md
 - SharePoint\SharePointOnline\information-architecture-modern-experience.md
 - SharePoint\SharePointOnline\plan-navigation-modern-experience.md
 - SharePoint\SharePointOnline\publishing-sites-classic-to-modern-experience.md
 - SharePoint\SharePointOnline\sharing-permissions-modern-experience.md

**Comment by dariomws306** [comment]
@OfficeGlobal Thank you!

**Comment by dariomws306** [comment]
Hi @OfficeGlobal , I have replaced "..." with "---" but the articles still have the same issue. PR was merged and I can see that it's applied in docs. But sill same issue.

Thanks for your help!

**Comment by OfficeGlobal** [comment]
Hello @dariomws306 , there is one more condition. I can see updated files in master branch, but to be able process updates it needs to be in Live branch too (we're getting files via iCMS and it's syncing the live branch)
